name: Power Platform CI/CD

on:
  push:
    branches:
      - "feature/**"
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changes:
    name: Detect Changes 
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.changes.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Detect branch changes
        id: changes
        uses: younited/detect-branch-changes-action@v0.1.3
        with:
          pathspec: |
            solutions/**
            src/**
            workflows/**

  build:
    name: Export Managed Solution
    runs-on: ubuntu-latest 
    needs: changes
    if: needs.changes.outputs.changed == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Get Power Platform secrets from Key Vault
        id: kv
        uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.AZURE_KEYVAULT_NAME }}
          secrets: |
            PP-DEV-ENV-URL
            PP-TENANT-ID
            PP-APP-ID
            PP-CLIENT-SECRET

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Export Solution (Managed)
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ secrets.PP-DEV-ENV-URL }}
          tenant-id: ${{ secrets.PP-TENANT-ID }}
          app-id: ${{ secrets.PP-APP-ID }}
          client-secret: ${{ secrets.PP-CLIENT-SECRET }}
          solution-name: aSolution
          managed: false
          solution-output-file: out/aSolution.zip

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: out/aSolution.zip
          solution-folder: solutions/aSolution/src
          overwrite-files: true

      - name: branch-solution (prepare repo for PR)
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: out/solutions/ALMLab
          solution-target-folder: solutions/ALMLab/src
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
